"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Logo } from "@/components/logo.tsx";
import { useCopy, useLanguage } from "@/lib/i18n/index.tsx";
import { SOLO_PRICE } from "@/lib/plans.ts";
import { SUPPORT, whatsappLink } from "@/lib/support.ts";

/**
 * The front door.
 *
 * Every screen shown here is a photograph of the running product, taken against
 * a seeded shop rather than drawn: the claim is that booking takes three
 * screens, and the honest way to make it is to show the three screens. They
 * live in `public/landing` and are regenerated by driving the app, so a screen
 * that changes shape can be re-taken rather than redrawn.
 *
 * Deliberately not `/`. That is the working application, and the day this
 * becomes the way in is a decision about the product rather than about a page —
 * one route change away, whenever somebody wants to make it.
 */

const CUSTOMER_STEPS = ["c1", "c2", "c3"] as const;
const OWNER_STEPS = ["o1", "o2", "o3", "o4"] as const;
const SHOT = {
  c1: "/landing/c1-search.jpg",
  c2: "/landing/c2-business.jpg",
  c3: "/landing/c3-booking.jpg",
  o1: "/landing/o1-month.jpg",
  o2: "/landing/o2-day.jpg",
  o3: "/landing/o3-panel.jpg",
  o4: "/landing/o4-team.jpg",
} as const;

/** How long a step holds before the tour moves itself along. */
const DWELL_MS = 5000;
const HERO_MS = 3600;

export default function Welcome() {
  const copy = useCopy("landing");
  const { language, toggleLanguage } = useLanguage();
  const [hero, setHero] = useState(0);
  const [customerAt, setCustomerAt] = useState(0);
  const [ownerAt, setOwnerAt] = useState(0);

  useEffect(() => {
    const timer = window.setInterval(
      () => setHero((at) => (at + 1) % CUSTOMER_STEPS.length),
      HERO_MS,
    );
    return () => window.clearInterval(timer);
  }, []);

  return (
    <div className="lp">
      <nav className="lp-nav">
        <div className="lp-wrap lp-navrow">
          <Link href="/welcome" aria-label="תור פנוי">
            <Logo />
          </Link>
          <span className="lp-links">
            <a href="#how">{copy.navHow}</a>
            <a href="#owners">{copy.navOwners}</a>
            <a href="#pricing">{copy.navPricing}</a>
            <a href="#contact">{copy.navContact}</a>
          </span>
          <span className="lp-navcta">
            <button className="lp-lang" onClick={toggleLanguage}>
              {language === "he" ? "EN" : "עב"}
            </button>
            <Link className="lp-btn lp-glow lp-sm" href="/">
              {copy.navCta}
            </Link>
          </span>
        </div>
      </nav>

      <header className="lp-hero">
        <div className="lp-wrap lp-herogrid">
          <div>
            <span className="lp-eyebrow">
              <i className="lp-pulse" />
              {copy.heroBadge}
            </span>
            <h1 className="lp-big">
              {copy.heroA}
              <br />
              <span className="lp-shine">{copy.heroB}</span>
            </h1>
            <p className="lp-lede">{copy.heroLede}</p>
            <div className="lp-actions">
              <Link className="lp-btn lp-glow lp-lg" href="/">
                {copy.heroCta1}
              </Link>
              <a className="lp-btn lp-ghost lp-lg" href="#owners">
                {copy.heroCta2}
              </a>
            </div>
          </div>

          <div className="lp-stage">
            <div className="lp-glowring" />
            <Screen src={SHOT[CUSTOMER_STEPS[hero] ?? "c1"]} alt={copy.hTitle} />
            <div className="lp-dots">
              {CUSTOMER_STEPS.map((step, at) => (
                <button
                  key={step}
                  className={at === hero ? "on" : undefined}
                  aria-label={String(at + 1)}
                  onClick={() => setHero(at)}
                />
              ))}
            </div>
          </div>
        </div>
      </header>

      <section id="how" className="lp-wrap lp-section">
        <span className="lp-kicker">{copy.kHow}</span>
        <h2 className="lp-h2">{copy.hTitle}</h2>
        <p className="lp-sub">{copy.hSub}</p>
        <Tour
          at={customerAt}
          onPick={setCustomerAt}
          steps={CUSTOMER_STEPS.map((step, i) => ({
            key: step,
            title: [copy.c1t, copy.c2t, copy.c3t][i] ?? "",
            body: [copy.c1b, copy.c2b, copy.c3b][i] ?? "",
            src: SHOT[step],
          }))}
        />
      </section>

      <section id="owners" className="lp-owners">
        <div className="lp-wrap lp-section">
          <span className="lp-kicker lp-cyan">{copy.kOwners}</span>
          <h2 className="lp-h2">{copy.oTitle}</h2>
          <p className="lp-sub">{copy.oSub}</p>
          <Tour
            at={ownerAt}
            onPick={setOwnerAt}
            steps={OWNER_STEPS.map((step, i) => ({
              key: step,
              title: [copy.o1t, copy.o2t, copy.o3t, copy.o4t][i] ?? "",
              body: [copy.o1b, copy.o2b, copy.o3b, copy.o4b][i] ?? "",
              src: SHOT[step],
            }))}
          />
          <div className="lp-actions" style={{ marginBlockStart: 36 }}>
            <Link className="lp-btn lp-glow lp-lg" href="/onboarding">
              {copy.oCta}
            </Link>
            <a className="lp-btn lp-ghost lp-lg" href="#contact">
              {copy.navContact}
            </a>
          </div>
        </div>
      </section>

      <section className="lp-wrap lp-section">
        <span className="lp-kicker">{copy.kWhy}</span>
        <div className="lp-feats">
          {[
            ["📍", copy.f1t, copy.f1b],
            ["⚡", copy.f2t, copy.f2b],
            ["🔔", copy.f3t, copy.f3b],
          ].map(([icon, title, body]) => (
            <div className="lp-feat" key={title}>
              <span className="lp-ico" aria-hidden="true">
                {icon}
              </span>
              <h3>{title}</h3>
              <p>{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="pricing" className="lp-wrap lp-section lp-centred">
        <span className="lp-kicker">{copy.kPricing}</span>
        <h2 className="lp-h2">{copy.pTitle}</h2>
        <p className="lp-sub">{copy.pSub}</p>
        {/* The number lives in lib/plans.ts, where the drawer and the pricing
            page also read it — a price quoted from two literals is a price
            that will disagree with itself. */}
        <div className="lp-price">
          <span className="lp-from">{copy.pFrom}</span>
          <b>₪{SOLO_PRICE}</b>
          <span className="lp-from">{copy.pPer}</span>
        </div>
        <Link className="lp-btn lp-solid lp-lg" href="/pricing">
          {copy.pAll}
        </Link>
      </section>

      <section id="contact" className="lp-contact">
        <div className="lp-wrap lp-section">
          <span className="lp-kicker">{copy.kContact}</span>
          <h2 className="lp-h2">{copy.ctTitle}</h2>
          <p className="lp-sub">{copy.ctSub}</p>
          {/* The numbers are configuration (ADR 0005) — the same ones support
              already answers on, rather than a second set written here. */}
          <div className="lp-ways">
            <a className="lp-way" href={whatsappLink()} target="_blank" rel="noopener">
              <span className="lp-ico" aria-hidden="true">💬</span>
              <span><b>{copy.ctWhatsapp}</b><span dir="ltr">{SUPPORT.whatsapp}</span></span>
            </a>
            <a className="lp-way" href={`tel:${SUPPORT.whatsapp}`}>
              <span className="lp-ico" aria-hidden="true">📞</span>
              <span><b>{copy.ctPhone}</b><span dir="ltr">{SUPPORT.whatsapp}</span></span>
            </a>
            <a className="lp-way" href={`mailto:${SUPPORT.email}`}>
              <span className="lp-ico" aria-hidden="true">✉️</span>
              <span><b>{copy.ctMail}</b><span dir="ltr">{SUPPORT.email}</span></span>
            </a>
            <div className="lp-way">
              <span className="lp-ico" aria-hidden="true">🕘</span>
              <span><b>{copy.ctHours}</b><span>{copy.ctHoursValue}</span></span>
            </div>
          </div>
        </div>
      </section>

      <section className="lp-wrap lp-section">
        <div className="lp-final">
          <h2 className="lp-h2">{copy.fTitle}</h2>
          <p>{copy.fSub}</p>
          <div className="lp-actions lp-centre">
            <Link className="lp-btn lp-glow lp-lg" href="/">
              {copy.fCta1}
            </Link>
            <Link className="lp-btn lp-ghost lp-lg" href="/onboarding">
              {copy.fCta2}
            </Link>
          </div>
        </div>
      </section>

      <footer className="lp-foot">
        <div className="lp-wrap lp-navrow">
          <Logo />
          <span>{copy.footNote}</span>
        </div>
      </footer>
    </div>
  );
}

/** One screen of the product, in the shell every screen here wears. */
const Screen = ({ src, alt }: { src: string; alt: string }) => (
  <div className="lp-phone">
    {/* Not next/image: these are fixed-width screenshots of a phone, and the
        loader's srcset would buy nothing a single well-sized JPEG does not. */}
    <img src={src} alt={alt} width={360} height={738} />
  </div>
);

type Step = { key: string; title: string; body: string; src: string };

/**
 * A row of steps beside the screen each one describes.
 *
 * It advances itself, and only while somebody is looking at it: a page that
 * animates where nobody is watching is a page spending a battery for nothing.
 */
const Tour = ({
  steps,
  at,
  onPick,
}: {
  steps: readonly Step[];
  at: number;
  onPick: (at: number) => void;
}) => {
  const [host, setHost] = useState<HTMLDivElement | null>(null);
  const [watching, setWatching] = useState(false);

  useEffect(() => {
    if (host === null) return;
    const eye = new IntersectionObserver(
      (entries) => setWatching(entries[0]?.isIntersecting === true),
      { threshold: 0.25 },
    );
    eye.observe(host);
    return () => eye.disconnect();
  }, [host]);

  useEffect(() => {
    if (!watching) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const timer = window.setTimeout(() => onPick((at + 1) % steps.length), DWELL_MS);
    return () => window.clearTimeout(timer);
  }, [watching, at, steps.length, onPick]);

  const shown = steps[at] ?? steps[0];
  return (
    <div className="lp-tour" ref={setHost}>
      <div className="lp-steps">
        {steps.map((step, i) => (
          <button
            key={step.key}
            className={i === at ? "lp-step on" : "lp-step"}
            aria-current={i === at}
            onClick={() => onPick(i)}
          >
            <span className="lp-no">{i + 1}</span>
            <span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
              <span className="lp-bar">
                <i />
              </span>
            </span>
          </button>
        ))}
      </div>
      {shown !== undefined && <Screen key={shown.key} src={shown.src} alt={shown.title} />}
    </div>
  );
};
