"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Logo } from "@/components/logo.tsx";
import { useCopy, useLanguage } from "@/lib/i18n/index.tsx";
import { SOLO_PRICE } from "@/lib/plans.ts";
import { SUPPORT, whatsappLink } from "@/lib/support.ts";

/**
 * The front door.
 *
 * Every screen shown here is a photograph of the running product, taken against
 * a seeded shop rather than drawn: the claim is that booking takes three
 * screens, and the honest way to make it is to show the three screens. They
 * live in `public/landing` and are regenerated by driving the app, so a screen
 * that changes shape can be re-taken rather than redrawn.
 *
 * Deliberately not `/`. That is the working application, and the day this
 * becomes the way in is a decision about the product rather than about a page —
 * one route change away, whenever somebody wants to make it.
 */

const CUSTOMER_STEPS = ["c1", "c2", "c3", "c4", "c5"] as const;
const OWNER_STEPS = ["o1", "o2", "o3", "o4", "o5"] as const;

/**
 * What the hero cycles.
 *
 * Not simply the first few of the tour: two steps of one journey can be the
 * same screen scrolled, which reads as a slideshow that is broken rather than
 * as a product with range. These three share nothing — searching, a map, the
 * appointments somebody already has.
 */
const HERO_STEPS = ["c1", "c2", "c5"] as const;

/**
 * Every screen, and how it is shown.
 *
 * Some of what this product does is a noun and some of it is a verb. A map is a
 * picture. "Search and filter" is not, and neither is "pick an hour and confirm
 * it" — a still of either is a screen caught mid-gesture, which is how the
 * first cut of this page ended up showing a half-scrolled screen with its top
 * sliced off. Those are short silent films of the real thing being used.
 *
 * The films are recorded by the same suite that takes the stills — see
 * e2e/landing-shots.spec.ts — so both stay true to the product together.
 */
const SHOT = {
  c1: { film: "/landing/c1-search.mp4", poster: "/landing/c1-search-poster.jpg" },
  c2: { still: "/landing/c2-map.jpg" },
  c3: { still: "/landing/c3-business.jpg" },
  c4: { film: "/landing/c4-book.mp4", poster: "/landing/c4-book-poster.jpg" },
  c5: { still: "/landing/c5-mine.jpg" },
  o1: { still: "/landing/o1-month.jpg" },
  o2: { still: "/landing/o2-day.jpg" },
  o3: { film: "/landing/o3-booking.mp4", poster: "/landing/o3-booking-poster.jpg" },
  o4: { still: "/landing/o4-customers.jpg" },
  o5: { still: "/landing/o5-panel.jpg" },
} as const;

type Shot = { still: string } | { film: string; poster: string };

const isFilm = (shot: Shot): shot is { film: string; poster: string } => "film" in shot;

/** How long a step holds before the tour moves itself along. */
const DWELL_MS = 5000;
const HERO_MS = 3600;

export default function Welcome() {
  const copy = useCopy("landing");
  const { language, toggleLanguage } = useLanguage();
  const [hero, setHero] = useState(0);
  const [customerAt, setCustomerAt] = useState(0);
  const [ownerAt, setOwnerAt] = useState(0);

  const nextHero = useCallback(
    () => setHero((at) => (at + 1) % HERO_STEPS.length),
    [],
  );
  const heroShot = SHOT[HERO_STEPS[hero] ?? "c1"];

  useEffect(() => {
    // A film says when it is done; a picture has to be told. Putting a clip on
    // the same fixed timer as a still would cut it off partway through the one
    // gesture it exists to show.
    if (isFilm(heroShot)) return;
    const timer = window.setTimeout(nextHero, HERO_MS);
    return () => window.clearTimeout(timer);
  }, [heroShot, nextHero]);

  return (
    <div className="lp">
      <nav className="lp-nav">
        <div className="lp-wrap lp-navrow">
          <Link href="/welcome" aria-label="תור פנוי">
            <Logo />
          </Link>
          <span className="lp-links">
            <a href="#how">{copy.navHow}</a>
            <a href="#owners">{copy.navOwners}</a>
            <a href="#pricing">{copy.navPricing}</a>
            <a href="#contact">{copy.navContact}</a>
          </span>
          <span className="lp-navcta">
            <button className="lp-lang" onClick={toggleLanguage}>
              {language === "he" ? "EN" : "עב"}
            </button>
            <Link className="lp-btn lp-glow lp-sm" href="/">
              {copy.navCta}
            </Link>
          </span>
        </div>
      </nav>

      <header className="lp-hero">
        <div className="lp-wrap lp-herogrid">
          <div>
            <span className="lp-eyebrow">
              <i className="lp-pulse" />
              {copy.heroBadge}
            </span>
            <h1 className="lp-big">
              {copy.heroA}
              <br />
              <span className="lp-shine">{copy.heroB}</span>
            </h1>
            <p className="lp-lede">{copy.heroLede}</p>
            <div className="lp-actions">
              <Link className="lp-btn lp-glow lp-lg" href="/">
                {copy.heroCta1}
              </Link>
              <a className="lp-btn lp-ghost lp-lg" href="#owners">
                {copy.heroCta2}
              </a>
            </div>
          </div>

          <div className="lp-stage">
            <div className="lp-glowring" />
            <Screen
              key={HERO_STEPS[hero]}
              shot={heroShot}
              alt={copy.hTitle}
              eager
              playing
              onFinished={nextHero}
            />
            <div className="lp-dots">
              {HERO_STEPS.map((step, at) => (
                <button
                  key={step}
                  className={at === hero ? "on" : undefined}
                  aria-label={String(at + 1)}
                  onClick={() => setHero(at)}
                />
              ))}
            </div>
          </div>
        </div>
      </header>

      <section id="how" className="lp-wrap lp-section">
        <span className="lp-kicker">{copy.kHow}</span>
        <h2 className="lp-h2">{copy.hTitle}</h2>
        <p className="lp-sub">{copy.hSub}</p>
        <Tour
          at={customerAt}
          onPick={setCustomerAt}
          steps={CUSTOMER_STEPS.map((step, i) => ({
            key: step,
            title: [copy.c1t, copy.c2t, copy.c3t, copy.c4t, copy.c5t][i] ?? "",
            body: [copy.c1b, copy.c2b, copy.c3b, copy.c4b, copy.c5b][i] ?? "",
            shot: SHOT[step],
          }))}
        />
      </section>

      <section id="owners" className="lp-owners">
        <div className="lp-wrap lp-section">
          <span className="lp-kicker lp-cyan">{copy.kOwners}</span>
          <h2 className="lp-h2">{copy.oTitle}</h2>
          <p className="lp-sub">{copy.oSub}</p>
          <Tour
            at={ownerAt}
            onPick={setOwnerAt}
            steps={OWNER_STEPS.map((step, i) => ({
              key: step,
              title: [copy.o1t, copy.o2t, copy.o3t, copy.o4t, copy.o5t][i] ?? "",
              body: [copy.o1b, copy.o2b, copy.o3b, copy.o4b, copy.o5b][i] ?? "",
              shot: SHOT[step],
            }))}
          />
          <div className="lp-actions" style={{ marginBlockStart: 36 }}>
            <Link className="lp-btn lp-glow lp-lg" href="/onboarding">
              {copy.oCta}
            </Link>
            <a className="lp-btn lp-ghost lp-lg" href="#contact">
              {copy.navContact}
            </a>
          </div>
        </div>
      </section>

      <section className="lp-wrap lp-section">
        <span className="lp-kicker">{copy.kWhy}</span>
        <div className="lp-feats">
          {[
            ["📍", copy.f1t, copy.f1b],
            ["⚡", copy.f2t, copy.f2b],
            ["🔔", copy.f3t, copy.f3b],
          ].map(([icon, title, body]) => (
            <div className="lp-feat" key={title}>
              <span className="lp-ico" aria-hidden="true">
                {icon}
              </span>
              <h3>{title}</h3>
              <p>{body}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="pricing" className="lp-wrap lp-section lp-centred">
        <span className="lp-kicker">{copy.kPricing}</span>
        <h2 className="lp-h2">{copy.pTitle}</h2>
        <p className="lp-sub">{copy.pSub}</p>
        {/* The number lives in lib/plans.ts, where the drawer and the pricing
            page also read it — a price quoted from two literals is a price
            that will disagree with itself. */}
        <div className="lp-price">
          <span className="lp-from">{copy.pFrom}</span>
          <b>₪{SOLO_PRICE}</b>
          <span className="lp-from">{copy.pPer}</span>
        </div>
        <Link className="lp-btn lp-solid lp-lg" href="/pricing">
          {copy.pAll}
        </Link>
      </section>

      <section id="contact" className="lp-contact">
        <div className="lp-wrap lp-section">
          <span className="lp-kicker">{copy.kContact}</span>
          <h2 className="lp-h2">{copy.ctTitle}</h2>
          <p className="lp-sub">{copy.ctSub}</p>
          {/* The numbers are configuration (ADR 0005) — the same ones support
              already answers on, rather than a second set written here. */}
          <div className="lp-ways">
            <a className="lp-way" href={whatsappLink()} target="_blank" rel="noopener">
              <span className="lp-ico" aria-hidden="true">💬</span>
              <span><b>{copy.ctWhatsapp}</b><span dir="ltr">{SUPPORT.whatsapp}</span></span>
            </a>
            <a className="lp-way" href={`tel:${SUPPORT.whatsapp}`}>
              <span className="lp-ico" aria-hidden="true">📞</span>
              <span><b>{copy.ctPhone}</b><span dir="ltr">{SUPPORT.whatsapp}</span></span>
            </a>
            <a className="lp-way" href={`mailto:${SUPPORT.email}`}>
              <span className="lp-ico" aria-hidden="true">✉️</span>
              <span><b>{copy.ctMail}</b><span dir="ltr">{SUPPORT.email}</span></span>
            </a>
            <div className="lp-way">
              <span className="lp-ico" aria-hidden="true">🕘</span>
              <span><b>{copy.ctHours}</b><span>{copy.ctHoursValue}</span></span>
            </div>
          </div>
        </div>
      </section>

      <section className="lp-wrap lp-section">
        <div className="lp-final">
          <h2 className="lp-h2">{copy.fTitle}</h2>
          <p>{copy.fSub}</p>
          <div className="lp-actions lp-centre">
            <Link className="lp-btn lp-glow lp-lg" href="/">
              {copy.fCta1}
            </Link>
            <Link className="lp-btn lp-ghost lp-lg" href="/onboarding">
              {copy.fCta2}
            </Link>
          </div>
        </div>
      </section>

      <footer className="lp-foot">
        <div className="lp-wrap lp-navrow">
          <Logo />
          <span>{copy.footNote}</span>
        </div>
      </footer>
    </div>
  );
}

/**
 * One screen of the product, in the shell every screen here wears.
 *
 * A still where a still will do, a film where the thing being shown is
 * something somebody does rather than something they look at. The film is
 * silent, inline and unstoppable by design — it is an illustration, not a
 * video somebody chose to watch — and it plays only while it is the screen on
 * show and somebody is looking at it.
 */
const Screen = ({
  shot,
  alt,
  eager = false,
  playing = false,
  onFinished,
}: {
  shot: Shot;
  alt: string;
  eager?: boolean;
  /** Whether this is the screen on show, and on somebody's screen. */
  playing?: boolean;
  onFinished?: (() => void) | undefined;
}) => (
  <div className="lp-phone">
    {isFilm(shot) ? <Film shot={shot} alt={alt} playing={playing} onFinished={onFinished} /> : (
      /* Not next/image: these are the 390x844 artboard at twice over, shown at
         one size on every viewport, so the loader's srcset would buy nothing a
         single well-sized JPEG does not.

         Eager only in the hero. The rest are three screens down the page, and
         making somebody wait for pictures they have not scrolled to is how a
         page about saving people time opens slowly. */
      <img
        src={shot.still}
        alt={alt}
        width={390}
        height={844}
        loading={eager ? "eager" : "lazy"}
        decoding="async"
      />
    )}
  </div>
);

const Film = ({
  shot,
  alt,
  playing,
  onFinished,
}: {
  shot: { film: string; poster: string };
  alt: string;
  playing: boolean;
  onFinished?: (() => void) | undefined;
}) => {
  const reel = useRef<HTMLVideoElement>(null);
  const still = usePrefersStillness();

  useEffect(() => {
    const player = reel.current;
    if (player === null) return;
    if (!playing || still) {
      player.pause();
      return;
    }
    player.currentTime = 0;
    // Autoplay is allowed for a muted inline video and refused otherwise; a
    // refusal leaves the poster up, which is the right thing to be left with.
    void player.play().catch(() => {});
  }, [playing, still, shot.film]);

  return (
    <video
      ref={reel}
      src={shot.film}
      poster={shot.poster}
      aria-label={alt}
      muted
      playsInline
      // Nothing is downloaded until the clip is wanted; the poster stands in.
      preload="none"
      // Somebody who has asked for stillness gets a picture and the means to
      // start it themselves, rather than a picture and no way in.
      controls={still}
      // A tour step waits for its clip to finish before moving on, so the clip
      // must end. Everywhere else it simply repeats.
      loop={onFinished === undefined}
      onEnded={onFinished}
      width={390}
      height={844}
    />
  );
};

/**
 * Whether the reader has asked the machine to stop moving things.
 *
 * Read through state rather than at render, because the server has no media
 * queries and a component that answers differently there and here is a
 * hydration mismatch. Stillness starts false and corrects itself on arrival,
 * which is the right way round: the correction stops a clip, it does not start
 * one.
 */
const usePrefersStillness = (): boolean => {
  const [still, setStill] = useState(false);

  useEffect(() => {
    const asked = window.matchMedia("(prefers-reduced-motion: reduce)");
    const follow = () => setStill(asked.matches);
    follow();
    asked.addEventListener("change", follow);
    return () => asked.removeEventListener("change", follow);
  }, []);

  return still;
};

type Step = { key: string; title: string; body: string; shot: Shot };

/**
 * A row of steps beside the screen each one describes.
 *
 * It advances itself, and only while somebody is looking at it: a page that
 * animates where nobody is watching is a page spending a battery for nothing.
 */
const Tour = ({
  steps,
  at,
  onPick,
}: {
  steps: readonly Step[];
  at: number;
  onPick: (at: number) => void;
}) => {
  const [host, setHost] = useState<HTMLDivElement | null>(null);
  const [watching, setWatching] = useState(false);

  useEffect(() => {
    if (host === null) return;
    const eye = new IntersectionObserver(
      (entries) => setWatching(entries[0]?.isIntersecting === true),
      { threshold: 0.25 },
    );
    eye.observe(host);
    return () => eye.disconnect();
  }, [host]);

  const shown = steps[at] ?? steps[0];
  const next = useCallback(
    () => onPick((at + 1) % steps.length),
    [at, steps.length, onPick],
  );

  useEffect(() => {
    if (!watching) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    // A step showing a film holds until the film is over — cutting away
    // halfway through the one gesture it exists to show would be worse than
    // not showing it.
    if (shown !== undefined && isFilm(shown.shot)) return;
    const timer = window.setTimeout(next, DWELL_MS);
    return () => window.clearTimeout(timer);
  }, [watching, shown, next]);

  return (
    <div className="lp-tour" ref={setHost}>
      <div className="lp-steps">
        {steps.map((step, i) => (
          <button
            key={step.key}
            className={i === at ? "lp-step on" : "lp-step"}
            aria-current={i === at}
            onClick={() => onPick(i)}
          >
            <span className="lp-no">{i + 1}</span>
            <span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
              <span className="lp-bar">
                <i />
              </span>
            </span>
          </button>
        ))}
      </div>
      {shown !== undefined && (
        <Screen
          key={shown.key}
          shot={shown.shot}
          alt={shown.title}
          playing={watching}
          onFinished={next}
        />
      )}
    </div>
  );
};
